// Copyright © Aptos Foundation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: aptos/remote_executor/v1/network_msg.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MessageType   string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMessage) Reset() {
	*x = NetworkMessage{}
	mi := &file_aptos_remote_executor_v1_network_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMessage) ProtoMessage() {}

func (x *NetworkMessage) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_remote_executor_v1_network_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMessage.ProtoReflect.Descriptor instead.
func (*NetworkMessage) Descriptor() ([]byte, []int) {
	return file_aptos_remote_executor_v1_network_msg_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *NetworkMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_aptos_remote_executor_v1_network_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_remote_executor_v1_network_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_aptos_remote_executor_v1_network_msg_proto_rawDescGZIP(), []int{1}
}

var File_aptos_remote_executor_v1_network_msg_proto protoreflect.FileDescriptor

const file_aptos_remote_executor_v1_network_msg_proto_rawDesc = "" +
	"\n" +
	"*aptos/remote_executor/v1/network_msg.proto\x12\x18aptos.remote_executor.v1\"M\n" +
	"\x0eNetworkMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\"\a\n" +
	"\x05Empty2w\n" +
	"\x15NetworkMessageService\x12^\n" +
	"\x11SimpleMsgExchange\x12(.aptos.remote_executor.v1.NetworkMessage\x1a\x1f.aptos.remote_executor.v1.Emptyb\x06proto3"

var (
	file_aptos_remote_executor_v1_network_msg_proto_rawDescOnce sync.Once
	file_aptos_remote_executor_v1_network_msg_proto_rawDescData []byte
)

func file_aptos_remote_executor_v1_network_msg_proto_rawDescGZIP() []byte {
	file_aptos_remote_executor_v1_network_msg_proto_rawDescOnce.Do(func() {
		file_aptos_remote_executor_v1_network_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aptos_remote_executor_v1_network_msg_proto_rawDesc), len(file_aptos_remote_executor_v1_network_msg_proto_rawDesc)))
	})
	return file_aptos_remote_executor_v1_network_msg_proto_rawDescData
}

var file_aptos_remote_executor_v1_network_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aptos_remote_executor_v1_network_msg_proto_goTypes = []any{
	(*NetworkMessage)(nil), // 0: aptos.remote_executor.v1.NetworkMessage
	(*Empty)(nil),          // 1: aptos.remote_executor.v1.Empty
}
var file_aptos_remote_executor_v1_network_msg_proto_depIdxs = []int32{
	0, // 0: aptos.remote_executor.v1.NetworkMessageService.SimpleMsgExchange:input_type -> aptos.remote_executor.v1.NetworkMessage
	1, // 1: aptos.remote_executor.v1.NetworkMessageService.SimpleMsgExchange:output_type -> aptos.remote_executor.v1.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aptos_remote_executor_v1_network_msg_proto_init() }
func file_aptos_remote_executor_v1_network_msg_proto_init() {
	if File_aptos_remote_executor_v1_network_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aptos_remote_executor_v1_network_msg_proto_rawDesc), len(file_aptos_remote_executor_v1_network_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aptos_remote_executor_v1_network_msg_proto_goTypes,
		DependencyIndexes: file_aptos_remote_executor_v1_network_msg_proto_depIdxs,
		MessageInfos:      file_aptos_remote_executor_v1_network_msg_proto_msgTypes,
	}.Build()
	File_aptos_remote_executor_v1_network_msg_proto = out.File
	file_aptos_remote_executor_v1_network_msg_proto_goTypes = nil
	file_aptos_remote_executor_v1_network_msg_proto_depIdxs = nil
}
